version: "3.5"

services:
    trexwebapp:
        #image: trexapp-image:latest
        build: .
        container_name: trexwebapp
        volumes: 
            - ./:/usr/local/app
        ports:
            - 8082:443
        networks:
            - trexnet    

networks: 
    trexnet:
        name: trexnet